insert into value_lists
(label,list,color,value,category,sort_order) values
	('Past Client', 'contact relationship', '#00AA55', null, null, 0),
	('Person I Know', 'contact relationship', '#AAFFAA', null, null, 2),
	('Vendor Partner', 'contact relationship', '#F3C800', null, null, 4),
	('Vendor Partner Reference', 'contact relationship', '#FF8080', null, null, 6),
	('Stranger: Not necessarily about RE', 'contact relationship', '#FFD5D5', null, null, 8),
	('Lead - Stranger (specifically about RE)', 'contact relationship', '#FF0000', null, null, 10),
	('Current Client (Currently Representing)', 'contact relationship', '#8000FF', null, null, 12),
	('SOI', 'contact how met', '#00AA55', null, 'SOI', 14),
	('SOI Referral', 'contact how met', '#AAFFAA', null, 'SOI', 16),
	('Past Client', 'contact how met', '#550000', null, 'RE Referral', 18),
	('Past Client Referral', 'contact how met', '#FF8080', null, 'RE Referral', 20),
	('Vendor Partner', 'contact how met', '#004040', null, 'VP', 22),
	('Vendor Partner Referral', 'contact how met', '#FA5000', null, 'VP', 24),
	('Vendor Partner Reference', 'contact how met', '#F0F000', null, 'VP', 26),
	('Paid Lead Source', 'contact how met', '#FF0000', null, 'RE Paid', 28),
	('Open House Visitor', 'contact how met', '#0000FF', null, 'RE Free', 30),
	('Sign Call', 'contact how met', '#008080', null, 'RE Free', 32),
	('Floor Time/Office Duty', 'contact how met', '#8000FF', null, 'RE Free', 34),
	('TREP Agent Referral', 'contact how met', '#5555FF', null, 'RE Referral', 36),
	('Agent Referral', 'contact how met', '#AAAAFF', null, 'RE Referral', 38),
	('Other', 'contact how met', '#CCCCCC', null, 'Other', 40),
	('In Person', 'convo method', '#AAFFAA', null, null, 42),
	('Phone: Connected', 'convo method', '#AAFFAA', null, null, 44),
	('Text', 'convo method', '#F0F000', null, null, 46),
	('Email', 'convo method', '#F0F000', null, null, 48),
	('Social Media DM', 'convo method', '#F0F000', null, null, 50),
	('Phone: Did NOT Connect', 'convo method', '#CCCCCC', null, null, 52),
	('Specific Reverse Problem Solve (No Deal In Pipeline)', 'convo main purpose', '#AAFFAA', null, null, 54),
	('Get Them On My VP List', 'convo main purpose', '#AAFFAA', null, null, 56),
	('Vet the Vendor', 'convo main purpose', '#AAFFAA', null, null, 58),
	('Deal In Pipeline (Specific Reverse Problem Solve)', 'convo main purpose', '#00AA55', null, null, 60),
	('Deal In Pipeline (Other Specific Reason Apart from Sale)', 'convo main purpose', '#00AA55', null, null, 62),
	('To Solve Their Problem (Peek)', 'convo main purpose', '#D5AAFF', null, null, 64),
	('Application Follow Up/Results of Vetting', 'convo main purpose', '#D5AAFF', null, null, 66),
	('Other Specific Reason (Not The Sale)', 'convo main purpose', '#D5AAFF', null, null, 68),
	('90 Day Check In (VP)', 'convo main purpose', '#8000FF', null, null, 70),
	('Service Call (Clients)', 'convo main purpose', '#8000FF', null, null, 72),
	('Unplanned Conversation', 'convo main purpose', '#CCCCCC', null, null, 74),
	('Other - Voxer Danielle (Coaching Students ONLY)', 'convo main purpose', '#FF0000', null, null, 76),
	('Informal - Cool, Casual, Personal', 'convo tone', '#AAFFAA', null, null, 78),
	('Formal - Strictly Business', 'convo tone', '#FF8080', null, null, 80),
	('N/A - Did not connect', 'convo tone', '#CCCCCC', null, null, 82),
	('Following Model - Deal Presented Itself!', 'convo model', '#00AA55', null, null, 84),
	('FORD questions', 'convo model', '#D5AAFF', null, null, 86),
	('Geo questions', 'convo model', '#AAFFAA', null, null, 88),
	('Forever home/Staying put question', 'convo model', '#5555FF', null, null, 90),
	('Asking about purpose of work done/being done', 'convo model', '#FF8080', null, null, 92),
	('How long do you plan on staying in this next home?', 'convo model', '#39398E', null, null, 94),
	('N/A deal not found', 'convo model', '#CCCCCC', null, null, 96),
	('Incoming Lead/Call', 'convo model', '#CCCCCC', null, null, 98),
	('OTHER - Voxer Danielle with what (Coaching Students ONLY)', 'convo model', '#FF0000', null, null, 100),
	('Yes, I tried to run the model', 'convo intentional', '#00AA55', null, null, 102),
	('Yes - even though I did not run the model, I got usable outcomes', 'convo intentional', '#AAFFAA', null, null, 104),
	('N/A - Left Vague Voicemail', 'convo intentional', '#F3C800', null, null, 106),
	('N/A - Was not a 2 way conversation', 'convo intentional', '#F3C800', null, null, 108),
	('N/A - Left voicemail (Not Vague Voicemail)', 'convo intentional', '#FF8080', null, null, 110),
	('No - Did not try to run the model and got no usable results', 'convo intentional', '#FF8080', null, null, 112),
	('N/A - Could NOT leave voicemail', 'convo intentional', '#CCCCCC', null, null, 114),
	('Yes', 'vp recommendation', '#AAFFAA', null, null, 116),
	('No - Asked but did not find', 'vp recommendation', '#F3C800', null, null, 118),
	('No - Chose not to ask on purpose', 'vp recommendation', '#F3C800', null, null, 120),
	('No - Forgot to ask', 'vp recommendation', '#FF8080', null, null, 122),
	('No - Avoided asking', 'vp recommendation', '#FF8080', null, null, 124),
	('No - Ran out of time', 'vp recommendation', '#CCCCCC', null, null, 126),
	('N/A - Did not connect', 'vp recommendation', '#CCCCCC', null, null, 128),
	('Yes', 'vp problem to solve', '#AAFFAA', null, null, 130),
	('No - Asked but did not find', 'vp problem to solve', '#F3C800', null, null, 132),
	('No - Chose not to ask on purpose', 'vp problem to solve', '#F3C800', null, null, 134),
	('No - Forgot to ask', 'vp problem to solve', '#FF8080', null, null, 136),
	('No - Avoided asking', 'vp problem to solve', '#FF8080', null, null, 138),
	('No - Ran out of time', 'vp problem to solve', '#CCCCCC', null, null, 140),
	('N/A - Did not connect', 'vp problem to solve', '#CCCCCC', null, null, 142),
	('Deal Found - Timeline Secured', 'deal found', '#00AA55', null, null, 144),
	('Deal Found - Timeline Not Secured', 'deal found', '#AAFFAA', null, null, 146),
	('Update Received on Deal In Pipeline', 'deal found', '#D5AAFF', null, null, 148),
	('N/A - Deal Not Found - Tried FORD/GEO - Nothing Heard', 'deal found', '#F3C800', null, null, 150),
	('N/A - Deal Not Found - Chose not to ask on purpose', 'deal found', '#F3C800', null, null, 152),
	('N/A - Deal Not Found - Forgot FORD/GEO', 'deal found', '#FF8080', null, null, 154),
	('N/A - Deal Not Found - Avoided FORD/GEO', 'deal found', '#FF8080', null, null, 156),
	('N/A - Deal Not Found - Ran Out of Time', 'deal found', '#CCCCCC', null, null, 158),
	('N/A - Did not connect', 'deal found', '#CCCCCC', null, null, 160),
	('Prospecting: Call', 'deal activity', '#FF0000', null, null, 162),
	('Prospecting: Text', 'deal activity', '#550000', null, null, 164),
	('Prospecting: Social Media Message', 'deal activity', '#004040', null, null, 166),
	('Prospecting: Email', 'deal activity', '#00AA55', null, null, 168),
	('Prospecting: In Person', 'deal activity', '#0000FF', null, null, 170),
	('Marketing: Direct Mail', 'deal activity', '#FFD5D5', null, null, 172),
	('Marketing: Paid Ads/Leads', 'deal activity', '#FF8080', null, null, 174),
	('Marketing: Social Media', 'deal activity', '#F3C800', null, null, 176),
	('Marketing: Email', 'deal activity', '#AAFFAA', null, null, 178),
	('Marketing: Listing', 'deal activity', '#AAAAFF', null, null, 180),
	('Floor Time', 'deal activity', '#CCCCCC', null, null, 182),
	('TREP', 'deal activity', '#00FF00', null, null, 184),
	('It came to me', 'deal discovered', '#D5AAFF', null, null, 186),
	('I found/discovered it in conversation', 'deal discovered', '#AAFFAA', null, null, 188),
	('Desire to own a home', 'deal move trigger', '#CCCCCC', null, null, 190),
	('Change in family situation', 'deal move trigger', '#CCCCCC', null, null, 192),
	('Desire for a larger home', 'deal move trigger', '#CCCCCC', null, null, 194),
	('Desire to be closer to family and friends', 'deal move trigger', '#CCCCCC', null, null, 196),
	('Change in family situation', 'deal move trigger', '#CCCCCC', null, null, 198),
	('Desire for a home in a better area', 'deal move trigger', '#CCCCCC', null, null, 200),
	('Job relocation or move', 'deal move trigger', '#CCCCCC', null, null, 202),
	('Desire for a smaller home', 'deal move trigger', '#CCCCCC', null, null, 204),
	('Retirement', 'deal move trigger', '#CCCCCC', null, null, 206),
	('Establishing a household', 'deal move trigger', '#CCCCCC', null, null, 208),
	('Desire to be closer to school/job/transit', 'deal move trigger', '#CCCCCC', null, null, 210),
	('Affordability', 'deal move trigger', '#CCCCCC', null, null, 212),
	('Financial Security', 'deal move trigger', '#CCCCCC', null, null, 214),
	('Desire for a newly built or custom home', 'deal move trigger', '#CCCCCC', null, null, 216),
	('Other', 'deal move trigger', '#CCCCCC', null, null, 218),
	('Buy Side', 'deal type', '#CCCCCC', null, null, 220),
	('List Side', 'deal type', '#CCCCCC', null, null, 222),
	('Tenant Rep', 'deal type', '#CCCCCC', null, null, 224),
	('Rental Listing', 'deal type', '#CCCCCC', null, null, 226),
	('Referral', 'deal type', '#CCCCCC', null, null, 228),
	('Prospect', 'deal pipeline stage', '#CCCCCC', null, null, 230),
	('Contact', 'deal pipeline stage', '#FFD5D5', null, null, 232),
	('Opportunity', 'deal pipeline stage', '#FF8080', null, null, 234),
	('Active Client', 'deal pipeline stage', '#F3C800', null, null, 236),
	('Under Contract', 'deal pipeline stage', '#AAFFAA', null, null, 238),
	('Closed', 'deal pipeline stage', '#00AA55', null, null, 240),
	('Lost', 'deal pipeline stage', '#333333', null, null, 242),
	('0-3 Months', 'deal timeline stated', '#CCCCCC', 2, null, 244),
	('3-6 Months', 'deal timeline stated', '#CCCCCC', 5, null, 246),
	('6-12 Months', 'deal timeline stated', '#CCCCCC', 8, null, 248),
	('12-18 Months', 'deal timeline stated', '#CCCCCC', 12, null, 250),
	('18-24 Months', 'deal timeline stated', '#CCCCCC', 18, null, 252),
	('24-36 Months', 'deal timeline stated', '#CCCCCC', 24, null, 254),
	('4 Years', 'deal timeline stated', '#CCCCCC', 40, null, 256),
	('5 Years', 'deal timeline stated', '#CCCCCC', 50, null, 258),
	('6 Years', 'deal timeline stated', '#CCCCCC', 60, null, 260),
	('7 Years', 'deal timeline stated', '#CCCCCC', 70, null, 262),
	('8 Years', 'deal timeline stated', '#CCCCCC', 80, null, 264),
	('10+ Years', 'deal timeline stated', '#CCCCCC', 90, null, 266),
	('Forever Home', 'deal timeline stated', '#CCCCCC', 180, null, 268),
	('3.5%', 'deal commission', '#00AA55', 0.035, null, 270),
	('3%', 'deal commission', '#00AA55', 0.03, null, 272),
	('2.5%', 'deal commission', '#AAFFAA', 0.025, null, 274),
	('2%', 'deal commission', '#F3C800', 0.02, null, 276),
	('1.5%', 'deal commission', '#F0F000', 0.015, null, 278),
	('1%', 'deal commission', '#FF8080', 0.01, null, 280),
	('1 month', 'deal commission', '#AAFFAA', 1, null, 282),
	('1K', 'deal commission', '#F3C800', 1000, null, 284),
	('No', 'y-n-ygood', '#FFD5D5', null, null, 286),
	('Yes', 'y-n-ygood', '#AAFFAA', null, null, 288),
	('No', 'y-n-na-ygood', '#AAFFAA', null, null, 290),
	('Yes', 'y-n-na-ygood', '#00AA55', null, null, 292),
	('N/A - Did not connect', 'y-n-na-ygood', '#CCCCCC', null, null, 294),
	('No', 'y-n-progress-ygood', '#FF0000', null, null, 296),
	('In Progress', 'y-n-progress-ygood', '#F3C800', null, null, 298),
	('Yes', 'y-n-progress-ygood', '#AAFFAA', null, null, 300),
	('N/A', 'y-n-progress-ygood', '#CCCCCC', null, null, 302),
	('Horrible','ranking','#803939',0,null,402),
('Very Poor','ranking','#9e6161',1,null,404),
('Poor','ranking','#cea1a1',2,null,406),
('OK','ranking','#f3c800',3,null,408),
('Good','ranking','#99ff00',4,null,410),
('Very Good','ranking','#73cf10',5,null,412),
('Great','ranking','#267030',6,null,414),
('Depressed','mindset','#803939',0,null,416),
('Anxious','mindset','#9e6161',1,null,418),
('Cautious','mindset','#cea1a1',2,null,420),
('Stable','mindset','#f3c800',3,null,422),
('Optimistic','mindset','#73cf10',5,null,426),
('Abundant','mindset','#267030',6,null,428);